export const SET_LOADER = "SET_LOADER";
export const CLOSE_LOADER = "CLOSE_LOADER";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESFULL = "LOGIN_SUCCESFULL";
export const SET_TOKEN = "SET_TOKEN";
export const REGISTER_SUCESSFULL = "REGISTER_SUCESSFULL";